### ISSUE TITLE
Result of the analysis is not seen in Problems window

### ISSUE THREAD

**Issue by tutejszy** [kwin/cppcheclipse#106]
I can run cppcheck on a project. It gives some errors in console, but Problems window is empty. I tried to restart Eclipse, review options, but no luck. Any thoughts?
Cppcheclipse version 1.1.1
Cppcheck 2.1
Eclipse Version: 2019-06 (4.12.0), Build id: 20190614-1200
I don't see any errors from cppcheclipse in Error Log window. 
Attached console log.
[cppcheclipse result.txt](https://github.com/kwin/cppcheclipse/files/4965542/cppcheclipse.result.txt)

**Comment by AntonKrug** [comment]
I think you do not have any errors, so nothing to display. The errors you see, it's just list of all supported tests/errors so you know what will be checked.

**Comment by AntonKrug** [comment]
Try add some bugs into your code, like this:

> int i = 4;
> while (i>2 || i<20) {
> //do something
> }

then change the int i =4; to just int i;

That could be 2 bugs

**Comment by tutejszy** [comment]
I tried it and still nothing. Contrary to Cppcheck application, which gives nice warning and style problem. Actually, the saved cppcheck application results file is vastly different. Not sure if this is normal. Attaching results from cppcheck application, you can compare to previously attached cppcheclipse result.
[cppcheck result.txt](https://github.com/kwin/cppcheclipse/files/5027813/cppcheck.result.txt)

**Comment by AntonKrug** [comment]
Now I see it, could you give it try with 1.83 version of cppcheck? It might be another format/parsing change as it happened in the past already and I know the 1.83 works.

**Comment by tutejszy** [comment]
Ok, I'm little dumb. Everything works even with newest version. The problem was general settings section that by default has no checks enabled. I would suggest that all the checks be enabled with the install by default, so the product works straight out the box. The cppcheck GUI does it, so I was perplexed seeing the difference. 
Thanks for great product!

**Comment by AntonKrug** [comment]
I'm not the author but my guess is that the author was trying to make it as less intrusive as possible and opt-in to as little as possible. And usually the first introductions to static code analysis finds a lot of broken stuff, it feels to me better to start with the bugs, then styling/performance/portability etc...

Working out of the box might not be always work, because you need to specify the cppcheck binary, it might not be in the default path, you might have multiple versions with different features installed and you want a specific version for the cppcheclipse, so I always seen it as some steps are necessary to configure it.

However it is possible to use macro in the path, and make the cppcheck part of the eclipse, preconfigure your workspace and your projects and then you can have portable setup which will work out of the box. 

Looks like you are happy enough, I will close the issue, if there is something else, feel free to re-open it.
